space_estimation_method: 'lm'
cache_dir: "./cache"
output_dir: "./output"
plots_dir: "./output/plots"
plots: false

# Inputs
inputs:
  land_use: "./data/land_use.csv"
  geometry: "./data/mgra15/mgra15.shp"
  raw_parking_inventory: "./data/mgra_parking_inventory.csv"

# Data input/outputs. These files serve as both inputs and output locations.

outputs:
  # reduced_parking_df: "./output/reduced_parking_costs.csv"     # Output from reduction and also input to imputation step
  imputed_parking_df: "./output/imputed_parking_costs.csv"     # Output from imputation and also input to district creation
  districts_df: "./output/district_data.csv"                     # Output from district creation and also input to aggregation
  # aggregated_street_data: "./output/aggregated_street_data.csv"   # Output from network data aggregation and input to space estimation
  estimated_spaces_df: "./output/estimated_spaces.csv"          # Output from space estimation
  expected_parking_df: './output/expected_parking_data.csv'       # Output
  combined_df: './output/final_parking_data.csv'                  # Output


# If you want to rename columns, you can do so here.
# Otherwise it return all columns (includes land_use columns))
output_columns: 
  expected_parking_df:  # The data frame that is output from the model
    # mgra:  # Index included by default
    # column name: optional new column name
    exp_hourly:
    exp_daily:
    exp_monthly:
    parking_type:
    spaces_for_calculation: parking_spaces
    estimated_spaces:
    spaces:


# Parameters
walk_dist: 0.5
walk_coef: -0.3

# Which models to run, comment out any that you wish to not run. 
# However, be sure that the input is ready for whatever the new first model is.
# For example, if you have parking data cleaned up already, it can be fed into the 'create_districts' model.
# Or if you manually estimated spaces, you can skip that model too.
models:
  - run_reduction
  - run_imputation
  - create_districts
  - run_space_estimation
  - run_expected_parking_cost
  - write_output
